CREATE TABLE ImportTest (
    importid INT64 NOT NULL,
    strCol STRING(100) NOT NULL,
    byteCol BYTES(100) NOT NULL,
    dateCol DATE NOT NULL,
	  tsCol TIMESTAMP NOT NULL,
    intCol INT64 NOT NULL,
	floatCol FLOAT64 NOT NULL,
) PRIMARY KEY (importid)
